### ISSUE TITLE
Material issue on FBX conversion

### ISSUE THREAD

**Issue by szymon-kwiatkowski-apzumi** [tappi287/usdzconvert_windows#1]
When converting from FBX file the output USDZ file have seethrough materials.
What i see is alpha on materials is set up to 0
FBX:
![image](https://user-images.githubusercontent.com/59923458/72970025-ffa45480-3dc6-11ea-84b3-0145453c5a17.png)
USDZ:
![image](https://user-images.githubusercontent.com/59923458/72970167-4f831b80-3dc7-11ea-8070-21d751e03868.png)

**Comment by szymon-kwiatkowski-apzumi** [comment]
I've managed to fix it temporarly for me by commenting 
            else:
                if input == usdUtils.InputName.opacity:
                    value = 1.0 - property.Get()[0]
                else:
                    value = float(property.Get()[0])

in processMaterialProperty in usdStageWithFbx.py, although i am sure it will cause other issues later on

**Comment by tappi287** [comment]
Hey there, first up I have to say that supporting the indivdiual usdzconvert functionality is outside the scope of this repository.

My guess for this particular problem would be that usdzconvert sets some inappropiate material values. You could work around this problem by specifying a default color per material as documented in the usdzconvert manual(https://github.com/tappi287/usdzconvert_webui/blob/master/usd_man/usdzconvert_manual.txt).
For easier conversion instead of fiddeling with the command line you could use this web ui: https://github.com/tappi287/usdzconvert_webui
Where I -plan- to integrate a color picker per material.

**Comment by tappi287** [comment]
> I've managed to fix it temporarly for me by commenting
> else:
> if input == usdUtils.InputName.opacity:
> value = 1.0 - property.Get()[0]
> else:
> value = float(property.Get()[0])
> 
> in processMaterialProperty in usdStageWithFbx.py, although i am sure it will cause other issues later on

Thanks for the info! In my converter web ui repository I manage those usdzconvert oddities with a "post process", basically a second conversion process that re-converts a usdc created with usdzconvert, instead of monkey patching usdzconvert itself which is maintained by Apple.

**Comment by szymon-kwiatkowski-apzumi** [comment]
Thanks for quick response! I'll keep this issue open for few days in case I occur any other issues.
